AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'scripts/*'
    - '*.gemspec'
    - 'Rakefile'
    - spec/support/003_factories.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Lint/DuplicateBranch:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

Style/OpenStructUse:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/simple-sql.rb
    - config/console-init.rb

Layout/HashAlignment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
