AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'lib/simple/store.old/**/*'
    - 'spec.old/**/*'
    - 'tasks/release.rake'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'scripts/*'
    - 'config/*'
    
Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false
  